name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: myci-actions/add-pacman-repo@5
      with:
        url: https://pkg.devkitpro.org/packages
        name: devkitpro
        keys: BC26F752D25B92CE272E0F44F7FD5492264BB9D0
        key-server: keyserver.ubuntu.com
        install: 3ds
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
